make_examplesfile<-function(dir_path = "notebook", file_name = "newfile.rmd")
{
  path<-paste0(dir_path,"/", file_name)
  file.create(path)
  writeLines(c('---',
              'title: "Report Title"',
              'date: "`r Sys.Date()`"',
              'output: html_document',
              '---',
              ' ',
              '```{r setup, include = FALSE}',
              'knitr::opts_chunk$set(',
              '  collapse = TRUE,',
              '  comment = "#>",',
              '  echo = TRUE, warning = FALSE, message = FALSE, error = TRUE, fig.width = 7, fig.asp = 0.9',
              ')',
              '```',
              ' ',
              ' ',
              '*Load required packages.*',
              ' ',
              '```{r, results="hide "}',
              'libraries<-c("PKNCA", "BEQR", "tidyverse")',
              'loadlibraries<-lapply(libraries, require, character.only=TRUE)',
              'rm(loadlibraries, libraries)',
              '```',
              ' ',
              ' ',
              ' ',
              '#Preparation of the PK dataset  ',
              ' ',
              '**Load dataset**   ',
              ' ',
              '```{r}',
              'data("beqrpkdataset")',
              'dim(beqrpkdataset)',
              'knitr::kable(head(beqrpkdataset, 5))',
              '```',
              ' ',
              '**Use the plot functions to explore the dataset**  ',
              ' ',
              '*Mean and 95%CI plots.*  ',
              '    ',
              '```{r}',
              'base_mean_plot(df=beqrpkdataset, treatment = "TREATMENT", time = "TAD", dv = "CONC")+',
              '  labs(x = "TIME", y="Conc(ng/mL)")+',
              '  scale_color_manual(name=NULL, values = c("REFERENCE" = "red", "TEST" = "blue"))+',
              '  labs(x="Time (hours)", y = "Concentrations (ng/mL)")+',
              '  facet_grid(PERIOD~TYPE, labeller = labeller(PERIOD=c("1"="Period 1", "2"= "Period 2")))+',
              '  BEQR_theme()+',
              '  theme(legend.position = "bottom", legend.key.width = unit(1, "cm"), legend.margin = margin(0,0,0,0))',
              '```',
              '    ',
              '*Individual plots.*  ',
              ' ',
              '*  *Faceted by analyte type and period.*  ',
              ' ',
              '```{r}',
              'plot_insulin(df=beqrpkdataset%>%filter(ID==1), id = "ID", visit = "PERIOD", idv = "TAD", form = "TREATMENT", dv=list(CONC="CONC"), ylab = "Concentration (ng/mL)", xlab = "Time(hrs)")+',
              '  facet_grid(PERIOD~TYPE, labeller = labeller(PERIOD=c("1"="Period 1", "2"= "Period 2")))',
              '```',
              '       ',
              '       ',
              '*  *Isolated analyte and period.*  ',
              " ",

              '```{r}',
              'plot_insulin(df=beqrpkdataset%>%filter(ID==1, TYPE=="INSULIN", PERIOD==1), id = "ID", visit = "PERIOD", idv = "TAD", form = "TREATMENT", dv=list(CONC="CONC"), ylab = "Concentration (ng/mL)", xlab = "Time(hrs)")',
              '```',
              '    ',
              ' ',
              '**Use the `adjust_insulin()` function to adjust for endogenous insulin production.**',
              ' ',
              '```{r}',
              'beqrpkdataset_adj<-beqrpkdataset%>%group_by(ID,PERIOD)%>%do(adjust_insulin(., idv = "TAD", dosing_time = 0.001, dv="CONC", dv_type = "TYPE", dv_type_values = list(INSULIN = "INSULIN", CPEPTIDE = "CPEPTIDE")))%>%ungroup()',
              ' ',
              'knitr::kable(head(beqrpkdataset_adj,10))',
              '```',
              ' ',
              ' ',
              '**Use plot functions to explore adjusted insulin.**',
              ' ',
              '*  *Use the `base_mean_plot` function.*',
              ' ',
              '```{r}',
              'base_mean_plot(df = beqrpkdataset_adj%>%filter(INCLUDED=="YES"), treatment = "TREATMENT", time = "TAD", dv = "INSULIN_ADJ")+',
              '  labs(x = "TIME", y="Adjusted insulin conc(ng/mL)")+',
              '  scale_color_manual(name=NULL, values = c("REFERENCE" = "red", "TEST" = "blue"))+',
              '  facet_grid(.~PERIOD, labeller = labeller(PERIOD=c("1"="Period 1", "2"= "Period 2")))+',
              '  BEQR_theme()+', '  theme(legend.position = "bottom", legend.key.width = unit(1, "cm"), legend.margin = margin(0,0,0,0))',
              '```',
              ' ',
              '* *Use `BEQR_theme()` function.*',
              ' ',
              '```{r}',
              'ggplot(data = beqrpkdataset_adj%>%filter(INCLUDED=="YES"), aes(x=TAD, y=INSULIN_ADJ, group=factor(ID)))+',
              '  geom_point(aes(color=TREATMENT),size=3, show.legend = FALSE)+',
              '  geom_line(aes(color=TREATMENT),size=1, show.legend = FALSE)+',
              '  scale_color_manual(name=NULL, values = c("REFERENCE" = "red", "TEST" = "blue"))+',
              '  labs(x="Time (hours)", y = "adjusted Insulin Concentrations (ng/mL)")+',
              '  facet_grid(.~TREATMENT)+',
              '  PKPDmisc::base_theme()+',
              '  BEQR::BEQR_theme()+',
              '  theme(legend.position = "bottom", legend.key.width = unit(1, "cm"), legend.margin = margin(0,0,0,0))',
              '```',
              " ",
              '**Use the `summarize_statz()` function to get descriptive statistics of insulin concentration.**',
              " ",
              '```{r}',
              'descInsulin<-beqrpkdataset_adj%>%filter(TAD>0)%>%group_by(TREATMENT,PERIOD,TAD)%>%do(summarize_statz(., group = "TREATMENT", variables = c("INSULIN_ADJ")))%>%ungroup()',
              'knitr::kable(head(descInsulin, 5), digits = 1)',
              '```',
              " ",
              " ",
              '#Preparation of the PD dataset  ',
              " ", '**Load the PD dataset.**  ',
              " ",
              '```{r}',
              'data("beqrpddataset")',
              'beqrpddataset<-beqrpddataset%>%filter(!is.na(TIME))',
              'knitr::kable(head(beqrpddataset, 5))',
              '```',
              " ",
              " ",
              '```{r}',
              '# Observation time are in 24hours format. Should be writen in a format that can be manipulated by R functions',
              'beqrpddataset<-beqrpddataset%>%mutate(CLOCK = ifelse(nchar(TIME)==1, paste0("000",TIME),',
              '                                        ifelse(nchar(TIME)==2, paste0("00", TIME),',
              '                                        ifelse(nchar(TIME)==3, paste0("0", TIME), TIME))))',
              '```',
              " ",
              '**Use the `str_punctuate()` function to add pantuation to clocktime.** ',
              " ",
              '```{r}',
              'beqrpddataset<-beqrpddataset%>%mutate(CLOCK = str_panctuate(CLOCK, 2, ":"))',
              '```',
              " ",
              " ",
              '```{r}',
              '# Any date can be used to help to calculate time after dose',
              'beqrpddataset<-beqrpddataset%>%mutate(DATE = lubridate::dmy("15-06-2000"))',
              '```',
              " ",
              '**Use the function `edit_Date()` to change date to next-date after midnight.**  ',
              " ",
              '```{r}',
              'beqrpddataset<-beqrpddataset%>%group_by(ID,PERIOD)%>%filter(!is.na(TIME))%>%',
              '  do(edit_Date(., condition_col = "TIME", date_col = "DATE"))%>%ungroup()',
              " ",
              '# A date-time is required to calculate time after dose',
              'beqrpddataset<-beqrpddataset%>%mutate(DATETIME=paste(DATE, CLOCK, sep=" "))%>%',
              '  mutate(CLOCKTIME=lubridate::ymd_hm(DATETIME))',
              " ",
              '# Get time after dose',
              'beqrpddataset<-beqrpddataset%>%arrange(ID,PERIOD,CLOCKTIME)%>%group_by(ID,PERIOD)%>%',
              '  mutate(TAD=as.numeric(round(difftime(CLOCKTIME, first(CLOCKTIME), units = "min"),6)),',
              '         GCLAMP=first(GLUCOSE)-9)%>%ungroup() # A clamp value is need for plotting glucose profile',
              " ",
              '##Select relevant columns',
              'beqrpddataset<-beqrpddataset%>%select(ID,PERIOD,TIME,TAD,SEQUENCE,TREATMENT,GIR,GLUCOSE,GCLAMP)',
              '```',
              " ",
              '**Use use the `custom_round()` function to round Time column to the nearest multiple of 5.**  ',
              " ",
              '```{r}',
              '#Round up time to multiples of 5',
              'beqrpddataset<-beqrpddataset%>%mutate(RTAD=ifelse(TAD<12*60, custom_round(TAD, 5, 2.5), custom_round(TAD, 10, 5)))',
              " ",
              '#Change time to hours',
              'beqrpddataset<-beqrpddataset%>%mutate(RTAD=round(RTAD/60,3))',
              " ",
              '##Make TIME BINS for plotting mean profiles',
              'beqrpddataset<-beqrpddataset%>%mutate(TIMEBIN=PKPDmisc::set_bins(RTAD, breaks = c(3/60, seq(4.9/60, 24, 9.9/60))))',
              " ",
              '#Get mean time within the time bin',
              'beqrpddataset<-beqrpddataset%>%group_by(ID, PERIOD, TIMEBIN)%>%mutate(MEANTAD = mean(RTAD, na.rm = TRUE))%>%ungroup()',
              '```',
              " ",
              '**Explore the infusion profiles.**  ',
              " ",
              '*  * Individual profiles.*  ',
              " ",
              '```{r}',
              'ggplot(data=beqrpddataset, aes(RTAD, GIR, group=ID))+',
              '  geom_line(aes(colour=TREATMENT))+',
              '  geom_point(aes(colour=TREATMENT))+',
              '  facet_grid(PERIOD~TREATMENT, labeller = labeller(PERIOD=c("1"="Period 1", "2"= "Period 2")))+',
              '  scale_color_manual(name=NULL, values = c("REFERENCE" = "red", "TEST" = "blue"))+',
              '  labs(y="Glucose infusion rate (mL/hr)",x="Time (hours)")+',
              '  BEQR_theme()+theme(legend.position = "bottom", legend.key.width = unit(1, "cm"), legend.margin = margin(0,0,0,0))',
              '```',
              '  ',
              '   ',
              '*  * Mean profiles by treatment.*  ',
              " ",
              '```{r}',
              '##Plot mean profiles',
              'ggplot(data = beqrpddataset, aes(x=RTAD, y=GIR, color=TREATMENT))+',
              '  stat_summary(fun.y = function(x)(mean(x, na.rm = TRUE)), geom = "point", size=3)+',
              '  stat_summary(fun.y = function(x)(mean(x, na.rm = TRUE)), geom = "line", size=1)+',
              '  #stat_summary(fun.data = function(x){data.frame(ymin=mean(x)-1.96*se(x), ymax=mean(x)+1.96*se(x))}, geom = "errorbar", width=1)+',
              '  scale_color_manual(name=NULL, values = c("REFERENCE" = "red", "TEST" = "blue"))+',
              '  labs(x="Time (hours)", y = "Glucose infusion rate (mL/hr)")+',
              '  facet_grid(.~PERIOD, labeller = labeller(PERIOD=c("1"="Period 1", "2"= "Period 2")))+',
              '  BEQR_theme()+theme(legend.position = "bottom", legend.key.width = unit(1, "cm"), legend.margin = margin(0,0,0,0))',
              '```',
              " ",
              '**Use the `get_smooth_dv()` function to get predicted infusion rate profiles.**  ',
              " ",
              '```{r}',
              'beqrpddataset<-beqrpddataset%>%group_by(ID,PERIOD)%>%do(get_smooth_dv(., idv = "TAD", dv= "GIR", span = 0.2))',
              'knitr::kable(head(beqrpddataset, 10))',
              '```',
              " ",
              'The figure below shows overlay of observed and predicted glucose infusion rate for one subject.   ',
              " ",
              '```{r}',
              'ggplot(beqrpddataset%>%filter(ID==1), aes(x=TAD, y=GIR))+',
              '  geom_line()+',
              '  geom_line(aes(y=smooth_dv), color="red")+',
              '  facet_grid(.~TREATMENT)+',
              '  BEQR_theme()',
              '```',
              " ",
              '**Plot predicted mean infusion rate profile using the `base_mean_plot()` function**',
              " ",
              '```{r}',
              'base_mean_plot(df=beqrpddataset, treatment = "TREATMENT", time = "RTAD", dv = "smooth_dv")+',
              '  scale_color_manual(name=NULL, values = c("REFERENCE" = "red", "TEST" = "blue"))+',
              '  labs(x="Time (hours)", y = "Glucose infusion rate (mL/hr)")+',
              '  facet_grid(.~PERIOD, labeller = labeller(PERIOD=c("1"="Period 1", "2"= "Period 2")))+',
              '  BEQR_theme()+theme(legend.position = "bottom", legend.key.width = unit(1, "cm"), legend.margin = margin(0,0,0,0))',
              '```',
              " ",
              '#Load the demographics dataset  ',
              " ",
              '```{r}',
              'data("beqrdemographic")',
              '```',
              " ",
              '**Use the `table_characteristics()` function to obtain a summary of demographic characteristics.** ',
              " ",
              '```{r, results="hide "}',
              'tab_char<-table_characteristics(vars = c("GENDER", "AGE", "WEIGHT"), strata = c("SEQUENCE", "TREATMENT"), includeNA = TRUE, data = beqrdemographic)',
              '```  ',
              " ",
              '```{r}',
              'knitr::kable(tab_char)',
              '```',
              " ",
              " ",
              '#Non compartmental Pharmacokinetic analysis',
              " ",
              '```{r}',
              '#Prepare the dataset for NCA',
              'insulinpk<-beqrpkdataset%>%',
              '  filter(TYPE=="INSULIN", !TIME%in%c("-30min","-20min","-10min"))%>%',
              '  select(ID,TREATMENT,PERIOD,SEQUENCE,TIME=TAD,CONC)',
              '```',
              " ",
              '**The PKNCA package has to be prepared to non-compartmental analysis.** ',
              " ",
              '```{r}',
              '# Method can be linear or log linear (default). Linear was chosen as required in FDA guidance',
              'PKNCA.options(auc.method="linear")',
              '# Check if method is set',
              'PKNCA.options(name = "auc.method")',
              '```',
              " ",
              '**PKNCA requires a template for partial AUC. Use `make_nca_par_dataset().`**',
              " ",
              '```{r}',
              '# We need names of NCA parameters computed by PKNCA',
              'ncaparams<-names(get.interval.cols())[-c(1,2)]',
              " ",
              " ",
              '# Create partial AUC dummy dataset based on names of nca params obtained.',
              'partialauc<-make_nca_par_dataset(nca_params = c("cmax","tmax","aumclast", "lambda.z","half.life","aucpext.obs"), ',
              '                             partial_aucs = list(start=c(0,0,0), end=c(4, 6, 12)), ',
              '                             protocol_tlast = 24, ',
              '                             compute_aucinf = TRUE)',
              '```',
              " ",
              " ",
              '**PKNCA requires a template dosing dataset. Use `make_nca_dose_dataset()`.**',
              " ",
              '```{r}',
              '#Dose was 0.4IU/Kg. Any dose value can be used since CL will not be computed.',
              'dose<-make_nca_dose_dataset(df = insulinpk, treatment_var = TREATMENT, id_var = ID, time_var = TIME, dose = 1, dose_time = 0, tau = 24)',
              '```',
              " ",
              " ",
              'NCA anlysis with the PKNCA package requires creation of CONC and dose data object separately and then join them partial AUC (Which contains NCAparameters to be computed). The code below is for creation of such objects. ',
              " ",
              '```{r}',
              '# Create Conc object',
              'myconc<-PKNCAconc(insulinpk, formula = CONC~TIME|TREATMENT+ID, ',
              '                  labels = c(TIME="Time (hrs)", CONC="Concentration (ng/mL)"),',
              '                  units = c(TIME="hrs", CONC="ng/mL"))',
              " ",
              '# The create the dose object',
              'mydose<-PKNCAdose(dose, formula = DOSE~TIME|TREATMENT+ID, units=c(DOSE="ng", TIME="hrs"), route="extravascular")',
              " ",
              '# Create data object',
              'mydata<-PKNCAdata(myconc, mydose, intervals=partialauc)',
              " ",
              '```',
              " ",
              '**Compute NCA parameters.**',
              " ",
              '```{r}',
              'myresults<-pk.nca(mydata)',
              '```',
              " ",
              '**Use the function `extract_nca_results()` to extract NCA results in a formart ready for bioequivalence analysis.**  ',
              " ",
              '```{r}',
              '#Extact calculated PK parameters',
              'results_wide_pk<-extract_nca_results(myresults, select_nca_param = c("auclast", "aucinf.obs","cmax","tmax","aumclast", "lambda.z","half.life","aucpext.obs"))',
              '```',
              " ",
              '**The descriptive statistics of the NCA parameters can be summarized using the `summarize_statz()` function.**',
              " ",
              '```{r}',
              '#Summarize',
              'nca_summary<-summarize_statz(results_wide_pk, group = "TREATMENT", variables = c("auclast0_4", "auclast0_6", "auclast0_24", "aucinf.obs0_Inf","cmax0_24"))',
              'knitr::kable(nca_summary, digits = 1)',
              '```',
              " ",
              '**The statistical comparizon of half-life and tmax for reference and test treatments can be obtained using the `table_median_tmax_thalf()`.**',
              " ",
              '```{r, error=TRUE}',
              '# This will give errors because for some subjects dont have values for both test and treatment',
              'tmaxthalf<-table_median_tmax_thalf(results_wide_pk, group = "TREATMENT", tmax = "tmax0_24", thalf = "half.life0_24")',
              " ",
              'results_wide_pairs<-results_wide_pk%>%group_by(ID)%>%mutate(N=n())%>%ungroup()%>%filter(N==2)%>%select(-N)',
              " ",
              '# This return expected results',
              'tmaxthalf<-table_median_tmax_thalf(results_wide_pairs, group = "TREATMENT", tmax = "tmax0_24", thalf = "half.life0_24")',
              " ",
              'knitr::kable(tmaxthalf)',
              '```',
              " ",
              " ",
              '**Prepare the PD dataset for NCA analysis.**',
              " ",
              '```{r}',
              '# Negative values of the smooth DV have to be replaced by 0',
              'insulinpd<-beqrpddataset%>%mutate(SMOOTHGIR=ifelse(smooth_dv<0,0,smooth_dv), TIME=TAD/60)%>%select(ID, PERIOD, SEQUENCE,TREATMENT, TIME, SMOOTHGIR,GIR)',
              '```',
              " ",
              " ",
              '**Prepare the PKNCA objects for computing NCA parameters for PD.**  ',
              " ",
              '```{r}',
              '# Create Conc object',
              'mypd<-PKNCAconc(insulinpd, formula = SMOOTHGIR~TIME|TREATMENT+ID, ',
              '                  labels = c(TIME="Time (hrs)", CONC="Infusion rate (mL/hour)"),',
              '                  units = c(TIME="hrs", CONC="mL/hour"))',
              " ",
              '# The create the dose object',
              'mydose<-PKNCAdose(dose, formula = DOSE~TIME|TREATMENT+ID, units=c(DOSE="ng", TIME="hrs"), route="extravascular")',
              " ",
              '# Create data object',
              'myPDdata<-PKNCAdata(mypd, mydose, intervals=partialauc)',
              " ",
              '```',
              " ",
              '**Compute NCA parameters for PD.**',
              " ",
              '```{r}',
              'myPDresults<-pk.nca(myPDdata)',
              '```',
              " ",
              " ",
              '**Use the function `extract_nca_results()` to extract PD NCA results in a formart ready for bioequivalence analysis.**  ',
              " ",
              " ",
              '```{r}',
              '#Extact calculated PK parameters',
              'results_wide_pd<-extract_nca_results(myPDresults, select_nca_param = c("auclast","cmax","tmax", "half.life"))',
              '```',
              " ",
              '**The descriptive statistics of the PD NCA parameters can be summarized using the `summarize_statz()` function**',
              " ",
              '```{r}',
              '#Summarize',
              'nca_summary_pd<-summarize_statz(results_wide_pd, group = "TREATMENT", variables = c("auclast0_4", "auclast0_6", "auclast0_24","cmax0_24"))',
              " ",
              'knitr::kable(nca_summary_pd, digits = 1)',
              '```',
              " ",
              '**The statistical comparizon of tmax for reference and test treatments can be obtained using the `table_median_tmax()`.**',
              " ",
              '```{r}',
              'results_wide_pairs_pd<-results_wide_pd%>%group_by(ID)%>%mutate(N=n())%>%ungroup()%>%filter(N==2)%>%select(-N)',
              " ",
              '# This return expected results', 'pd_tmax_median<-table_median_tmax(results_wide_pairs_pd, group = "TREATMENT", tmax = "tmax0_24")', " ", 'knitr::kable(pd_tmax_median)',
              '```',
              " ",
              " ",
              '#Average bioequivalence comparison for PK parameters.  ',
              " ",
              " ",
              '```{r}',
              'results_wide_pk<-results_wide_pk%>%mutate_at(.vars = c("PERIOD", "TREATMENT", "SEQUENCE"), .funs = as.factor)',
              " ",
              " ",
              'fit_cmax<-get_abe_bylme(data = results_wide_pk, treatments = TREATMENT, sequences = SEQUENCE, periods = PERIOD, idvar = ID, abe_param = cmax0_24, reference = "REFERENCE")',
              " ",
              'ABEcmax<-fit_cmax$ABEresult',
              'ABEcmax<-ABEcmax%>%mutate(PARAMETERS = "Cmax")%>%select(PARAMETERS,GMR:WSV)',
              " ",
              'fit_auc24<-get_abe_bylme(data = results_wide_pk, treatments = TREATMENT, sequences = SEQUENCE, periods = PERIOD, idvar = ID, abe_param = auclast0_24, reference = "REFERENCE")  ',
              " ",
              'ABEauc24<-fit_auc24$ABEresult  ',
              'ABEauc24<-ABEauc24%>%mutate(PARAMETERS = "AUC0-24")%>%select(PARAMETERS, GMR:WSV)',
              'results<-bind_rows(ABEcmax, ABEauc24)',
              " ",
              'knitr::kable(results)',
              " ",
              '```',
              " ",
              " ",
              '#Average bioequivalence comparison for PD parameters.  ',
              " ",
              " ",
              '```{r}',
              'results_wide_pd<-results_wide_pd%>%mutate_at(.vars = c("PERIOD", "TREATMENT", "SEQUENCE"), .funs = as.factor)',
              " ",
              " ",
              'fit_girmax<-get_abe_bylme(data = results_wide_pd, treatments = TREATMENT, sequences = SEQUENCE, periods = PERIOD, idvar = ID, abe_param = cmax0_24, reference = "REFERENCE")',
              " ",
              'ABEgirmax<-fit_girmax$ABEresult',
              'ABEgirmax<-ABEgirmax%>%mutate(PARAMETERS = "GIRmax")%>%select(PARAMETERS,GMR:WSV)',
              " ",
              " ",
              'fit_girauc24<-get_abe_bylme(data = results_wide_pk, treatments = TREATMENT, sequences = SEQUENCE, periods = PERIOD, idvar = ID, abe_param = auclast0_24, reference = "REFERENCE")  ',
              " ",
              'ABEgirauc24<-fit_girauc24$ABEresult  ',
              'ABEgirauc24<-ABEgirauc24%>%mutate(PARAMETERS = "GIRAUC0-24")%>%select(PARAMETERS, GMR:WSV)',
              " ",
              'girresults<-bind_rows(ABEgirmax, ABEgirauc24)',
              " ",
              'knitr::kable(girresults)',
              " ",
              '```',
              " "),
            con = path)
}
